Type: "AWS::EC2::Instance"
Properties:
  AvailabilityZone: { "Fn::Select": [0,{ "Fn::GetAZs": "" }] }
  InstanceType: { 'Ref': 'InstanceType' }
  ImageId: { 'Ref': 'LatestAmiId' }
  IamInstanceProfile: { 'Ref': 'Ec2IAMProfile' }
  NetworkInterfaces: 
    - AssociatePublicIpAddress: "true"
      DeviceIndex: "0"
      GroupSet: 
        - {"Ref": "PrometheusSecurityGroup"}
      SubnetId: {"Ref": "KafkaPublicSubnet"}
  KeyName: !Join [ "-", [ {"Ref": "KeyPairName"}, { 'Ref': 'AWS::Region' } ] ]
  Tags:
    - Key: Name
      Value: Prometheus Instance
  UserData:
    Fn::Base64: !Sub 
    - |
      #!/bin/bash -xe
      
      # Update and install Prometheus
      sudo yum update -y
      sudo yum install -y wget

      sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
      sudo chmod +x /usr/local/bin/yq

      yq --version

      sudo useradd --no-create-home --shell /bin/false prometheus
      sudo mkdir /etc/prometheus
      sudo mkdir /var/lib/prometheus

      PROM_VERSION=${prometheusVersion}

      # Download and extract
      wget https://github.com/prometheus/prometheus/releases/download/v$PROM_VERSION/prometheus-$PROM_VERSION.linux-amd64.tar.gz
      tar xvf prometheus-$PROM_VERSION.linux-amd64.tar.gz
      
      # Move binaries
      sudo cp prometheus-$PROM_VERSION.linux-amd64/prometheus /usr/local/bin/
      sudo cp prometheus-$PROM_VERSION.linux-amd64/promtool /usr/local/bin/
      
      # Set ownership
      sudo chown prometheus:prometheus /usr/local/bin/prometheus
      sudo chown prometheus:prometheus /usr/local/bin/promtool
      
      # Create config file
      sudo touch /etc/prometheus/prometheus.yml

      sudo sh -c 'cat << EOF >> /etc/prometheus/prometheus.yml
      global:
        scrape_interval: 15s
      
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
      EOF'

      sudo chown -R prometheus:prometheus /etc/prometheus
      sudo chown prometheus:prometheus /var/lib/prometheus
      
      sudo cat <<EOF > /etc/systemd/system/prometheus.service
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
      [Install]
      WantedBy=multi-user.target
      EOF
    - prometheusVersion: { "Fn::Sub": [ "${prometheusVersion}", { "prometheusVersion": "${env:PROMETHEUS_VERSION}" } ] }