Type: "AWS::EC2::Instance"
Properties:
  AvailabilityZone: !Select [ 0, !GetAZs '' ]
  InstanceType: { 'Ref': 'InstanceType' }
  ImageId: { 'Ref': 'LatestAmiId' }
  SecurityGroupIds:
    - { 'Fn::GetAtt': ['PrometheusSecurityGroup', 'GroupId'] }
  KeyName: !Join [ "-", [ {"Ref": "KeyPairName"}, { 'Ref': 'AWS::Region' } ] ]
  IamInstanceProfile:
    Arn: { 'Fn::GetAtt': ['Ec2IAMProfile', 'Arn'] }
  Tags:
    - Key: Name
      Value: Prometheus Instance
  UserData:
    Fn::Base64: !Sub 
    - |
      #!/bin/bash -xe
      
      # Update and install Prometheus
      sudo yum update -y
      sudo yum install -y wget
      wget https://github.com/prometheus/prometheus/releases/download/v2.33.0/prometheus-2.33.0.linux-amd64.tar.gz
      tar xvf prometheus-2.33.0.linux-amd64.tar.gz
      mv prometheus-2.33.0.linux-amd64/ prometheus-file

      sudo useradd --no-create-home --shell /bin/false prometheus
      sudo mkdir /etc/prometheus
      sudo mkdir /var/lib/prometheus
      sudo chown prometheus:prometheus /etc/prometheus
      sudo chown prometheus:prometheus /var/lib/prometheus

      sudo cp prometheus-files/prometheus /usr/local/bin/
      sudo cp prometheus-files/promtool /usr/local/bin/
      sudo chown prometheus:prometheus /usr/local/bin/prometheus
      sudo chown prometheus:prometheus /usr/local/bin/promtool

      sudo cp -r prometheus-files/consoles /etc/prometheus
      sudo cp -r prometheus-files/console_libraries /etc/prometheus
      sudo chown -R prometheus:prometheus /etc/prometheus/consoles
      sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries

      sudo chown prometheus:prometheus /etc/prometheus/prometheus.yml
      
      sudo cat <<EOF > /etc/systemd/system/prometheus.service
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries
      
      [Install]
      WantedBy=multi-user.target
      EOF
    - nodeId: { "Fn::Sub": [ "${nodeId}", { "nodeId": 1 } ] }