Type: "AWS::EC2::Instance"
Properties:
  AvailabilityZone: { "Fn::Select": ["0", { "Fn::GetAZs": { "Ref": "AWS::Region" } }] }
  InstanceType: { 'Ref': 'InstanceType' }
  ImageId: { 'Ref': 'LatestAmiId' }
  SecurityGroupIds:
    - { 'Fn::GetAtt': ['PrometheusSecurityGroup', 'GroupId'] }
  KeyName: !Join [ "-", [ {"Ref": "KeyPairName"}, { 'Ref': 'AWS::Region' } ] ]
  IamInstanceProfile:
    Arn: { 'Fn::GetAtt': ['Ec2IAMProfile', 'Arn'] }
  Tags:
    - Key: Name
      Value: Prometheus Instance
  UserData:
    Fn::Base64: !Sub 
    - |
      #!/bin/bash -xe
      
      # Update and install Prometheus
      sudo yum update -y
      sudo yum install -y wget
      wget https://github.com/prometheus/prometheus/releases/download/v2.33.0/prometheus-2.33.0.linux-amd64.tar.gz
      tar xvf prometheus-2.33.0.linux-amd64.tar.gz
      cd prometheus-2.33.0.linux-amd64/
      
      # Start Prometheus
      ./prometheus --config.file=prometheus.yml

    - nodeId: { "Fn::Sub": [ "${nodeId}", { "nodeId": 1 } ] }