SASL_SCRAM_USERNAME: ${env:SASL_SCRAM_USERNAME}
SASL_SCRAM_PASSWORD: ${env:SASL_SCRAM_PASSWORD}
KEY_PAIR_BUCKET_NAME: ${env:KEY_PAIR_BUCKET_NAME}
KEY_PAIR_NAME: ${env:KEY_PAIR_NAME}
STATE: ${env:STATE}
COUNTRY: ${env:COUNTRY}
ORGANIZATION_UNIT: ${env:ORGANIZATION_UNIT}
CITY: ${env:CITY}
VPC_ID: ${env:VPC_ID}