SASL_SCRAM_USERNAME: ${env:SASL_SCRAM_USERNAME}
SASL_SCRAM_PASSWORD: ${env:SASL_SCRAM_PASSWORD}
KEY_PAIR_BUCKET_NAME: ${env:KEY_PAIR_BUCKET_NAME}
KEY_PAIR_NAME: ${env:KEY_PAIR_NAME}
STATE: ${env:STATE}
COUNTRY: ${env:COUNTRY}
ORGANIZATION_UNIT: ${env:ORGANIZATION_UNIT}
CITY: ${env:CITY}
KAFKA_REQUEST_TOPIC: ${env:KAFKA_REQUEST_TOPIC}
KAFKA_BOOTSTRAP_SERVER: ${env:KAFKA_BOOTSTRAP_SERVER}
KAFKA_REQUEST_CONSUMER_GROUP_ID: ${env:KAFKA_REQUEST_CONSUMER_GROUP_ID}
NODE_ONE_TOPIC: ${env:NODE_ONE_TOPIC}
NODE_TWO_TOPIC: ${env:NODE_TWO_TOPIC}
NODE_THREE_TOPIC: ${env:NODE_THREE_TOPIC}
OFFSETS_TOPIC_REPLICATION_FACTOR: ${env:OFFSETS_TOPIC_REPLICATION_FACTOR}
DEFAULT_REPLICATION_FACTOR: ${env:DEFAULT_REPLICATION_FACTOR}
SNS_ARN: { "Fn::Sub": ["${SnsArn}", { "SnsArn": { "Ref": "ApacheKafkaSNSTopic" } }] } #${env:SNS_TOPIC_NAME}
SNS_TOPIC_NAME: { "Fn::Select": [5, {"Fn::Split": [":", {"Ref": "ApacheKafkaSNSTopic"}]} ] }
KAFKA_BOOTSTRAP_SERVER_TWO: ${env:KAFKA_BOOTSTRAP_SERVER_TWO}
KAFKA_BOOTSTRAP_SERVER_THREE: ${env:KAFKA_BOOTSTRAP_SERVER_THREE}
STAGE: ${env:STAGE}
TABLE_NAME: { "Fn::Sub": ["${TableName}", { "TableName": { "Ref": "ConnectionsTable" } }] } #${env:TABLE_NAME}
REST_API_ENDPOINT_URI:
  {
    "Fn::Sub":
      [
        "https://${RestApiId}.execute-api.${AWS::Region}.amazonaws.com/${env:STAGE}",
        { "RestApiId": { "Ref": "WebSocketAPI" } },
      ],
  }