name: 'Deploy'
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

jobs:
  Deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SASL_SCRAM_USERNAME: ${{ secrets.SASL_SCRAM_USERNAME }}
      SASL_SCRAM_PASSWORD: ${{ secrets.SASL_SCRAM_PASSWORD }}
      KEY_PAIR_BUCKET_NAME: ${{ secrets.KEY_PAIR_BUCKET_NAME }}
      KEY_PAIR_NAME: ${{ secrets.KEY_PAIR_NAME }}
      STATE: ${{ secrets.STATE }}
      COUNTRY: ${{ secrets.COUNTRY }}
      ORGANIZATION_UNIT: ${{ secrets.ORGANIZATION_UNIT }}
      CITY: ${{ secrets.CITY }}
      VPC_ID: ${{ secrets.VPC_ID }}
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        cache: true
    
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install the latest serverless
      run: npm i serverless -g
    
    - uses: evantorrie/mott-the-tidier@v1-beta
      with:
        gomods: |
          **/go.mod
          go.mod
          -tools/go.mod
  
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-fix go.sum discrepancies
      
    # This step builds the Go application and creates a zip file containing the binary
    # It is important to note that the binary must be named "bootstrap"
    - name: Build Go application
      run: |    
        rm -rf build && make build && make zip

    - name: Create Key Pair
      run: |
        chmod +x ./shell-scripts/create-key-pair.sh
        ./shell-scripts/create-key-pair.sh
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        KEY_PAIR_BUCKET_NAME: ${{ secrets.KEY_PAIR_BUCKET_NAME }}
        KEY_PAIR_NAME: ${{ secrets.KEY_PAIR_NAME }}

    - name: Serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --verbose

    # - name: Update EC2 Launch Template Version
    #   run: |
    #     chmod +x ./shell-scripts/modify-launch-template-version.sh
    #     ./shell-scripts/modify-launch-template-version.sh
    #   env:
    #     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    
    # - name: Connect Kafka Cluster And Run Commands
    #   run: |
    #     chmod +x ./shell-scripts/ec2.sh
    #     ./shell-scripts/ec2.sh
    #   env:
    #     SASL_SCRAM_PASSWORD: ${{ secrets.SASL_SCRAM_PASSWORD }}
    #     SASL_SCRAM_USERNAME: ${{ secrets.SASL_SCRAM_USERNAME }}
    #     REGION: ${{ secrets.AWS_REGION }}
